CREATE DATABASE COLLEGE;
CREATE DATABASE IF NOT EXISTS COLLEGE;
CREATE DATABASE TEMP1;
DROP database if exists TEMP1;
USE  COLLEGE;
create table STUDENT(
ID INT primary KEY, NAME varchar(50),AGE INT NOT NULL);
insert into STUDENT values(1,"LEWRA",21);
INSERT INTO STUDENT VALUES(2,"POSCHAT",19);
INSERT INTO STUDENT(ID,NAME,AGE) VALUES
(3,"RUMI",22),
(4,"AZIZ",23),
(5,"RAFI",22);
SELECT * FROM STUDENT;
show databases;
SHOW TABLES;
CREATE TABLE EMPLOYEE(
ID INT , SALARY INT default 25000);
insert into EMPLOYEE(ID) values(12);
SELECT * FROM EMPLOYEE;
CREATE TABLE SCHOLERSHIP(ID INT primary KEY,NAME VARCHAR(50) ,GRADE decimal(3,2) NOT NULL,CITY varchar(20));
INSERT INTO SCHOLERSHIP VALUES
(112,"QUADER",4.00,"DHAKA"),(1121,"PATWARI",4.00,"DHAKA"),(1122,"NASIR",4.00,"CHOTTOGRAM"),
(102,"SULTAN",4.00,"DHAKA"),(114,"SULAIMAN",4.00,"CUMILLA"),(113,"SADIKA",4.00,"BORISHAL"),(132,"SALMAN",4.00,"KHULNA");
insert INTO SCHOLERSHIP VALUES(2212,"RASEL",3.96,"RAJSHAHI");
INSERT INTO SCHOLERSHIP VALUES(100,"RANA",4.00,"RAJSHAHI");
SELECT * FROM SCHOLERSHIP;
SELECT NAME,CITY FROM SCHOLERSHIP;
SELECT DISTINCT CITY FROM SCHOLERSHIP;
SELECT * FROM SCHOLERSHIP WHERE GRADE<4.00; 
SELECT * FROM SCHOLERSHIP WHERE CITY="DHAKA"; 
SELECT * FROM SCHOLERSHIP WHERE GRADE>3.96 AND CITY="DHAKA";
SELECT * FROM SCHOLERSHIP WHERE GRADE BETWEEN 3.99 AND 4.00;
SELECT * FROM SCHOLERSHIP WHERE CITY NOT IN ("DHAKA");
SELECT * FROM SCHOLERSHIP  WHERE GRADE>3.99 LIMIT 3;
SELECT * FROM SCHOLERSHIP order by ID ASC;


SELECT MAX(NAME) FROM SCHOLERSHIP ;
SELECT MAX(ID) FROM SCHOLERSHIP ;
SELECT AVG(GRADE) FROM SCHOLERSHIP ;
SELECT COUNT(ID) FROM SCHOLERSHIP ;


SELECT CITY,NAME,COUNT(ID)  FROM SCHOLERSHIP GROUP BY CITY,NAME ;
SELECT CITY,COUNT(ID)  FROM SCHOLERSHIP GROUP BY CITY ;
SELECT GRADE,COUNT(ID) FROM SCHOLERSHIP group by GRADE ORDER BY GRADE;
SELECT CITY,COUNT(CITY) FROM SCHOLERSHIP GROUP BY CITY HAVING MAX(GRADE)>3.99; 

SELECT NAME FROM SCHOLERSHIP WHERE CITY="RAJSHAHI" GROUP BY NAME HAVING MAX(GRADE)<4.00 ORDER BY ID ASC;

SET SQL_SAFE_UPDATES=0;

UPDATE SCHOLERSHIP SET CITY="DACCA" WHERE CITY="DHAKA";
UPDATE SCHOLERSHIP SET GRADE=GRADE+0.01 WHERE GRADE BETWEEN 0.00 AND 3.99;

DELETE FROM SCHOLERSHIP WHERE GRADE<3.00;

create table DEPT(ID int primary key,NAME varchar(50));
insert into DEPT values (111,"DSA"),(112,"WEB");
select * FROM DEPT;
update DEPT 
SET ID=113
WHERE ID=112;
create table TEACHER(ID INT PRIMARY KEY,NAME VARCHAR(50),DEPT_ID INT,foreign key (DEPT_ID) references DEPT(ID)
on update cascade
on delete cascade);
Insert into TEACHER values (111,"ZOHIR",111),(112,"RAIHAN",112);
select * FROM TEACHER;

ALTER TABLE TEACHER 
ADD column AGE INT;
ALTER TABLE TEACHER 
DROP column AGE;
ALTER TABLE SCHOLERSHIP 
ADD column AGE INT NOT NULL default 20;
